version : '3'

services:
    jenkins:
        image: jenkins/jenkins:jdk11
        container_name: jenkins
        ports:
        - "8880:8080"
        - "50000:50000"
        volumes:
        - ../volumes/jenkins:/var/jenkins_home
        networks:
        - docker_network

    ubuntu:
        build: 
            context: ../dockerfiles/slave/
        volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
        container_name: ubuntu
        depends_on:
        - jenkins
        networks:
        - docker_network
        command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Slave/slave-agent.jnlp -secret 350a7ab7b8f9b69a045e3fab78d18c23e515dd69e8703f4eb97b3d5068667d5b -workDir "/home/"
    
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        container_name: artifactory
        ports:
        - "8081:8081"
        - "8082:8082"
        volumes:
        - ../volumes/artifactory:/var/opt/jfrog/artifactory
        networks:
        - docker_network
    
    seleniumhub:
        image: selenium/hub
        container_name: seleniumhub
        ports:
        - "4444:4444"
        networks:
        - docker_network
    
    seleniumnode:
        image: selenium/node-firefox
        container_name: seleniumnode
        depends_on:
        - seleniumhub
        environment:
        - HUB_HOST=seleniumhub
        - HUB_PORT=4444
        networks:
        - docker_network

networks:
    docker_network:
        driver: bridge